#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QTranslator>
#include <QObject>
#include <QDebug>

class TranslationManager : public QObject {
    Q_OBJECT
    QGuiApplication* m_app;
    QQmlApplicationEngine* m_engine;
    QTranslator m_translator;

public:
    TranslationManager(QGuiApplication* app, QQmlApplicationEngine* engine, QObject* parent = nullptr)
        : QObject(parent), m_app(app), m_engine(engine) {}

    Q_INVOKABLE void setLanguage(const QString &lang) {
        m_app->removeTranslator(&m_translator);

        if (lang == "Arabic" || lang == "ar") {
            // Check all potential resource paths generated by CMake
            bool loaded = m_translator.load(":/qt/qml/task4/i18n/task4_ar.qm")
                          || m_translator.load(":/qt/qml/task4/i18n/qml_ar.qm")
                          || m_translator.load(":/i18n/qml_ar.qm")
                          || m_translator.load(":/i18n/task4_ar.qm");

            if (loaded) {
                m_app->installTranslator(&m_translator);
                qDebug() << "SUCCESS: Arabic translation loaded!";
            } else {
                qWarning() << "WARNING: Could not locate compiled .qm translation file in resources!";
            }

            // Mirror app layout for Arabic (Right-To-Left)
            m_app->setLayoutDirection(Qt::RightToLeft);
        } else {
            // Standard Left-To-Right for English
            m_app->setLayoutDirection(Qt::LeftToRight);
        }

        // Trigger UI update across all QML bindings containing qsTr()
        m_engine->retranslate();
    }
};

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);

    // Resolves QSettings initialization warnings
    app.setOrganizationName("ShopEaseApp");
    app.setOrganizationDomain("shopease.com");
    app.setApplicationName("ShopEase");

    QQmlApplicationEngine engine;

    TranslationManager transManager(&app, &engine);
    engine.rootContext()->setContextProperty("translationManager", &transManager);

    const QUrl url(u"qrc:/qt/qml/task4/Main.qml"_qs);
    QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                     &app, [url](QObject *obj, const QUrl &objUrl) {
                         if (!obj && url == objUrl)
                             QCoreApplication::exit(-1);
                     }, Qt::QueuedConnection);

    engine.load(url);

    return app.exec();
}

#include "main.moc"
